export const GAME_CONSTANTS = {

    MAX_INVENTORY_SIZE: 50,

    STARTING_HEALTH: 100,

    STARTING_ECHOES: 0,

    SCENE_TRANSITION_COVER_MS: 500,

    SCENE_TRANSITION_DURATION_MS: 1000,

    TYPEWRITER_CHARACTER_DELAY_MS: 28

};
